:PROPERTIES:
:ID:       920edd04-f411-4bea-8370-f179750071a7
:END:
#+title: L'arche Store
#+category: LarcheStore
#+filetags: Project

* Goals
Create a react web application that will be a webstore for L'Arche Cape Breton using the
Shoppify command line interface to connect the web app to the Shoppify backend.

* Website outline
The web application landing page will be a features page where new or sale items can be featured. From there the users can click on various themed tabs that will include things such as Artwork, weaving, cards, clothing and from there items hould be displayed programatically on cards that have a thumbnail picture of items, a short description, the price and so on. When those cards are clicked
on it should take the users to a page dedicated to that items speicifcally where there can be space for more or larger pictures, longer description etc. The users should be able to select in store pickup for items so there should be a page that displays the location and contact information for the store possibly using a simple google maps embed, phone number, information section etc. I will also need to set up a cart, user authentication, both of  which will presumably will be handled by the shoppify backend be handled by the Shoppigy backend. 

* Resources and Links
- [[https://github.com/chrisandrewca/shopify-nextjs][Example simple nextjs app]]

* Tasks
** ACTIVE  Add a text position toggle to carousel schema in sanity.
** ACTIVE create page template for each person
** PLAN Create news and events compontent
** PLAN Helmet for SEO 
- State "DONE"       from "PLAN"       [2022-02-05 Sat 02:53]
** PLAN create link dropdowns
** PLAN create an aside bar for social media integration
** PLAN Landing page
- featured items, welcome etc.
* Backlog
- State "DONE"       from "PLAN"       [2022-01-22 Sat 04:49]
* Dates
* Cancelled

* Sanity
** Sanity page definition
*** Title
*** slug
*** Page Category (About, How to help etc.)
*** Link
How the page appears in navs
*** tab
How the page appears in the tab
*** Author
*** Date
*** Rich Text
**** Text
**** Images
**** image aside 
**** Files
**** Video
** Sanity Post Definition 
*** Title
*** Post Category (News, Events, Jobs etc.)
*** slug
*** Main Image
*** Main Video
*** Author
*** Date
*** Rich Text
