:PROPERTIE:
:ID: 920edd04-f411-4bea-8370-f179750071a7
:END:
#+title: L'arche Store
#+category: LarcheStore
#+filetags: Project

* Goals
Create a react web application that will be a webstore for L'Arche Cape Breton, including a web store, that maximizes the amount of content on the website that is editable through a CMS.

* Website outline
The web application landing page will be a features page where new or sale items can be featured. From there the users can click on various themed tabs that will include things such as artwork, weaving, cards, clothing and from there items hould be displayed programatically on cards that have a thumbnail picture of items, a short description, the price and so on. When those cards are clicked on it will take the users to a page dedicated to that item where there is space for more or larger pictures, longer description etc. Users are able to select in-store pickup for items so there should be a page that displays the location and contact information for the store possibly using a simple google maps embed, phone number, information section etc. 
